blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogPostListView.as_view(), name='list'),
    path('<slug:slug>/', views.BlogPostDetailView.as_view(), name='detail'),
    path('create/', views.BlogPostCreateView.as_view(), name='create'),
    path('<slug:slug>/update/', views.BlogPostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.BlogPostDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryProductsView.as_view(), name='category_products'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/', views.AddToCartView.as_view(), name='add_to_cart'),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    manufactured_at = models.DateField(default=timezone.now)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'product')
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return f"{self.user.username} - {self.product.name}"


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    content = models.TextField()
    preview_image = models.ImageField(upload_to='blog_images', null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_published = models.BooleanField(default=False)
    views_count = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'blog_posts'
    queryset = BlogPost.objects.filter(is_published=True)

class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost_detail.html'
    context_object_name = 'blog_post'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj

class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'catalog/blogpost_form.html'
    fields = ['title', 'content', 'preview_image', 'is_published']
    success_url = reverse_lazy('blog:list')

class BlogPostUpdateView(UpdateView):
    model = BlogPost
    template_name = 'blog/blogpost_form.html'
    fields = ['title', 'content', 'preview_image', 'is_published']
    success_url = reverse_lazy('blog:list')

class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'blog/blogpost_confirm_delete.html'
    success_url = reverse_lazy('blog:list')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DetailView, View, ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, redirect
from .models import Product, Cart, Category

# Home Page
class HomeView(TemplateView):
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context

# Product List Page
class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'

# Product Detail Page
class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'

# Contacts Page
class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

# Cart Page
class CartView(TemplateView):
    template_name = 'catalog/cart.html'

# Add to Cart
class AddToCartView(LoginRequiredMixin, View):
    def post(self, request):
        product_id = request.POST.get('product_id')
        product = get_object_or_404(Product, id=product_id)

        # Add product to cart
        cart_item, created = Cart.objects.get_or_create(
            user=request.user,
            product=product,
            defaults={'quantity': 1}
        )

        if not created:
            cart_item.quantity += 1
            cart_item.save()

        # Redirect to cart page or home page
        return redirect('cart')

# Category Products Page
class CategoryProductsView(TemplateView):
    template_name = 'catalog/category_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        context['category'] = category
        context['products'] = Product.objects.filter(category=category)
        return context

templates/catalog/_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'catalog:home' %}">Skystore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:product_list' %}">Каталог</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:contacts' %}">Контакты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:cart' %}">Корзина</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/_menu.html' %}

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/catalog/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Blog Post</h1>
    <p>Are you sure you want to delete the blog post "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'blog:list' %}">Cancel</a>
    </form>
{% endblock %}

templates/catalog/blogpost_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ blog_post.title }}</h1>
    <p>{{ blog_post.created_at }}</p>
    <p>Views: {{ blog_post.views_count }}</p>
    {% if blog_post.preview_image %}
        <img src="{{ blog_post.preview_image.url }}" alt="{{ blog_post.title }}">
    {% endif %}
    <p>{{ blog_post.content }}</p>
{% endblock %}

templates/catalog/blogpost_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create/Update Blog Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/catalog/blogpost_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Blog Posts</h1>
    <ul>
        {% for blog_post in blog_posts %}
            <li>
                <a href="{% url 'blog:detail' blog_post.slug %}">{{ blog_post.title }}</a>
                <p>{{ blog_post.created_at }}</p>
                <p>{{ blog_post.content|truncatewords:20 }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/catalog/cart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Cart</h1>
    <ul>
        {% for cart_item in cart_items %}
            <li>
                {{ cart_item.product.name }} - {{ cart_item.quantity }} x {{ cart_item.product.price }}
            </li>
        {% empty %}
            <li>Your cart is empty.</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/catalog/category_products.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ category.name }}</h1>
    <p>{{ category.description }}</p>
    <ul>
        {% for product in products %}
            <li>
                <a href="{% url 'catalog:product_detail' product.slug %}">{{ product.name }}</a> - {{ product.price }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'catalog:contacts' %}" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 col-sm-6 mb-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ product.description|truncatewords:100 }}</p>
                    <p>Цена: {{ product.price }} руб.</p>
                    <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-md-6">
      {% if product.image %}
      <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
      {% else %}
      <img src="/static/img/no-image.jpg" alt="{{ product.name }}" class="img-fluid">
      {% endif %}
    </div>
    <div class="col-md-6">
      <h1>{{ product.name }}</h1>
      <p>{{ product.description }}</p>
      <p>Цена: {{ product.price }} руб.</p>
      <p>Артикул: {{ product.slug }}</p>
      <p>Дата производства: {{ product.manufactured_at|date:"d.m.Y" }}</p>
      <p>Статус: {% if product.available %}В наличии{% else %}Нет в наличии{% endif %}</p>
      <p>Создано: {{ product.created|date:"d.m.Y" }}</p>
      <p>Обновлено: {{ product.updated|date:"d.m.Y" }}</p>
      <a href="{% url 'add_to_cart' product.id %}" class="btn btn-primary">Добавить в корзину</a>
    </div>
  </div>
</div>
{% endblock %}